baseURL = "https://cabo-paradise.netlify.app/"
languageCode = "en-us"
title = "Welcome to Cabo Verde - Your little paradise"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "G-KKH621D4WP" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo.png"

# Gestion des langues : FR / EN / NL / DE / PT
[[Params.listeLangues]]
code = "en"
[[Params.listeLangues]]
code = "pt"
[[Params.listeLangues]]
code = "nl"

# meta data
author = "BVIT Webdesign"
description = "Design and context by BVIT Webdesign"

# Gestion des langues : FR / EN / NL / DE / PT
[Languages]
############ 1 - Site in NEDERLANDS
[Languages.nl]
weight = 1
languageCode = "nl-nl"
title = " Nederlandse versie website"
dateFormat = "2 January 2006"

home = "Home"
logo = "images/logo.png"
menufixed = false

footerDescription = "Wij zijn Cabo Paradise."
footerServiceTitle = "Diensten"
footerQuicklinkTitle = "Links"
footerAboutTitle = "Over ons"
footerSubscribeTitle = "Registreer"

# Hero Area Section
[Languages.nl.params.hero]
enable = true
heading = "NEDERLANDS Geniet van uw stukje paradijs op aarde"
description = "NL Versie - Een heerlijk stukje paradijs op aarde - Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
button = true
btnText = "Meer weten"
btnURL = "/#"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL = "https://youtu.be/alyKpwrx-2k?feature=shared"

# About 2 Section
[Languages.nl.params.aboutSm]
enable = true
title = "Het beste online wat Cabo Verde te brengen heeft"
description = "hier komt nog een tekst met beelden om de sfeer weer te geven"

# Blog Section On Homepage
[Languages.nl.params.blog]
enable = true
topTitle = "Paradise Gems"
title = "Blog"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.nl.params.contact]
enable = true
topTitle = "Contacteer Ons"
title = "Contacteer ons"
subtitle = "Gebruik dit formulier om al je (aan)vragen te doen rond de website. Wij zullen u snel van antwoord zijn"
address = "14/05, Santa Maria <br> Sal , Cabo Verde"
phone = "+238 xx xx xx  or +32 478 800 401"
fax = "no fax"
facebook = "https://www.facebook.com/caboparadise"
twitter = "https://twitter.com/caboparadise"
linkedin = "https://www.linkedin.com/caboparadise"
dribbble = "https://dribbble.com/"
instagram = "https://www.instagram.com/caboparadise"
mapLatitude = "16.598275"
mapLongitude = "-22.914787"
mapMarker = "images/marker.png"

# Call to Action Section on About Page
[Languages.nl.params.cta]
enable = true
bg = "images/call-to-action/call-to-action-bg-2.jpg"
title = "Laat ons je levensdroom inkleuren. Wij zorgen voor je stek zodat je maximaal kan genieten van het paradijs"
subtitle = "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Ons contacteren"

############# 2 - Site en ENGLISH
[Languages.en]
weight = 2
languageCode = "en-us"
title = "Cabo Verde Paradise"
dateFormat = "January 2, 2006"
home = "Home"
logo = "images/logo.png"
menufixed = false

footerDescription = "Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
footerServiceTitle = "Service"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "About"
footerSubscribeTitle = "Subscribe"


# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable = true
heading = "We love to build your paradise in Cabo"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
button = true
btnText = "Know More"
btnURL = "/#"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL = "https://youtu.be/alyKpwrx-2k?feature=shared"

# About 2 Section
[Languages.en.params.aboutSm]
enable = true
title = "We have explored for you all the secrets of the archipel"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

# Blog Section On Homepage
[Languages.en.params.blog]
enable = true
topTitle = "Cabo Paradise Revealed"
title = "Paradise Blog."
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.en.params.contact]
enable = true
topTitle = "DROP US A NOTE"
title = "Contact Us."
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
address = "14/05, Santa Maria <br> Sal , Cabo Verde"
phone = "fix number"
fax = "no fax"
facebook = "https://www.facebook.com/caboparadise"
twitter = "https://twitter.com/caboparadise"
linkedin = "https://www.linkedin.com/caboparadise"
dribbble = "https://dribbble.com/"
instagram = "https://www.instagram.com/caboparadise"
mapLatitude = "16.598275"
mapLongitude = "-22.914787"
mapMarker = "images/marker.png"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable = true
bg = "images/call-to-action/call-to-action-bg-2.jpg"
title = "Let's Create Something Together"
subtitle = "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Contact Us"

############# 2 - Site en PORTUGUESE
[Languages.pt]
weight = 3
languageCode = "pt-pt"
title = "Cabo Verde Paradisio"
dateFormat = "January 2, 2006"
home = "Home"
logo = "images/logo.png"
menufixed = false

footerDescription = "Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
footerServiceTitle = "Serviços"
footerQuicklinkTitle = "Ligações "
footerAboutTitle = "Sobre Nos"
footerSubscribeTitle = "Subscrever"



# Hero Area Section
[Languages.pt.params.hero]
enable = true
heading = "Adoramos construir o seu paraíso no Cabo"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
button = true
btnText = "Saber Mais"
btnURL = "/#"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL = "https://youtu.be/alyKpwrx-2k?feature=shared"

# About 2 Section
[Languages.pt.params.aboutSm]
enable = true
title = "We have explored for you all the secrets of the archipel"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

# Blog Section On Homepage
[Languages.pt.params.blog]
enable = true
topTitle = "Cabo Paraíso revelado"
title = "Paraiso Blog."
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.pt.params.contact]
enable = true
topTitle = "Deixe-nos uma nota"
title = "Contacte-nos."
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
address = "14/05, Santa Maria <br> Sal , Cabo Verde"
phone = "fix number"
fax = "no fax"
facebook = "https://www.facebook.com/caboparadise"
twitter = "https://twitter.com/caboparadise"
linkedin = "https://www.linkedin.com/caboparadise"
dribbble = "https://dribbble.com/"
instagram = "https://www.instagram.com/caboparadise"
mapLatitude = "16.598275"
mapLongitude = "-22.914787"
mapMarker = "images/marker.png"

# Call to Action Section on About Page
[Languages.pt.params.cta]
enable = true
bg = "images/call-to-action/call-to-action-bg-2.jpg"
title = "Let's Create Something Together"
subtitle = "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name = "about"
url = "about/"
weight = 2
[[menu.nav]]
name = "service"
url = "service/"
weight = 3
[[menu.nav]]
name = "portfolio"
url = "portfolio/"
weight = 4
[[menu.nav]]
name = "blog"
url = "blog/"
weight = 5
[[menu.nav]]
name = "contact"
url = "contact/"
weight = 6

# Footer Service Menu
[[menu.service]]
name = "realestate-service"
url = "service/"
weight = 1
[[menu.service]]
name = "webdesign"
url = "service/"
weight = 2
[[menu.service]]
name = "webdevelopment"
url = "service/"
weight = 3

# Footer Quick links Menu
[[menu.quicklink]]
name = "partners"
url = "about/"
weight = 1
[[menu.quicklink]]
name = "about"
url = "about/"
weight = 2
[[menu.quicklink]]
name = "faqs"
url = "about/"
weight = 3
[[menu.quicklink]]
name = "badges"
url = "about/"
weight = 4
